# Join Statements - Lab

## Introduction

In this lab, you'll practice your knowledge of `JOIN` statements, using various types of joins and various methods for specifying the links between them.

## Objectives

You will be able to:
- Write queries that make use of various types of Joins
- Join tables using foreign keys

## CRM Schema

In almost all cases, rather then just working with a single table you will typically need data from multiple tables. 
Doing this requires the use of **joins** using shared columns from the two tables. 

In this lab, you'll use the same Customer Relationship Management (CRM) database that you saw from the previous lesson.
<img src='images/Database-Schema.png' width="600">

## Connecting to the Database
Import the necessary packages and connect to the database **data.sqlite**.

In [29]:
import pandas as pd
import sqlite3
conn = sqlite3.connect('data.sqlite')
cur = conn.cursor()

## Display the names of all the employees in Boston.
Hint: join the employees and offices tables.

In [30]:
employee = pd.DataFrame(cur.execute("""SELECT * FROM employees""").fetchall())
employee.columns = [i[0] for i in cur.description]
employee.head(3)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing

In [31]:
offices = pd.DataFrame(cur.execute("""SELECT * FROM offices""").fetchall())
offices.columns = [i[0] for i in cur.description]
offices.head(3)

,officeCode,city,phone,addressLine1,addressLine2,state,country,postalCode,territory
0,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
1,2,Boston,+1 215 837 0825,1550 Court Place,Suite 102,MA,USA,02107,NA
2,3,NYC,+1 212 555 3000,523 East 53rd Street,apt. 5A,NY,USA,10022,NA

In [45]:
employee_offices = pd.DataFrame(cur.execute("""SELECT  * FROM employees
                                JOIN offices 
                                ON employees.officeCode = offices.officeCode;""").fetchall())
employee_offices.columns = [i[0] for i in cur.description]
employee_offices

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,officeCode,city,phone,addressLine1,addressLine2,state,country,postalCode,territory
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC),6,Sydney,+61 2 9264 2451,5-11 Wentworth Avenue,Floor #2,,Australia,NSW 2010,APAC
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA),4,Paris,+33 14 723 4404,43 Rue Jouffroy D'abbans,,,France,75017,EMEA
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA),1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep,2,Boston,+1 215 837 0825,1550 Court Place,Suite 102,MA,USA,02107,NA
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep,2,Boston,+1 215 837 0825,1550 Court Place,Suite 102,MA,USA,02107,NA
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep,3,NYC,+1 212 555 3000,523 East 53rd Street,apt. 5A,NY,USA,10022,NA
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep,3,NYC,+1 212 555 3000,523 East 53rd Street,apt. 5A,NY,USA,10022,NA
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep,4,Paris,+33 14 723 4404,43 Rue Jouffroy D'abbans,,,France,75017,EMEA
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep,4,Paris,+33 14 723 4404,43 Rue Jouffroy D'abbans,,,France,75017,EMEA
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102,Sales Rep,4,Paris,+33 14 723 4404,43 Rue Jouffroy D'abbans,,,France,75017,EMEA
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep,7,London,+44 20 7877 2041,25 Old Broad Street,Level 7,,UK,EC2N 1HN,EMEA
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102,Sales Rep,7,London,+44 20 7877 2041,25 Old Broad Street,Level 7,,UK,EC2N 1HN,EMEA
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088,Sales Rep,6,Sydney,+61 2 9264 2451,5-11 Wentworth Avenue,Floor #2,,Australia,NSW 2010,APAC
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088,Sales Rep,6,Sydney,+61 2 9264 2451,5-11 Wentworth Avenue,Floor #2,,Australia,NSW 2010,APAC
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep,6,Sydney,+61 2 9264 2451,5-11 Wentworth Avenue,Floor #2,,Australia,NSW 2010,APAC
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056,Sales Rep,5,Tokyo,+81 33 224 5000,4-1 Kioicho,,Chiyoda-Ku,Japan,102-8578,Japan
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep,5,Tokyo,+81 33 224 5000,4-1 Kioicho,,Chiyoda-Ku,Japan,102-8578,Japan
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102,Sales Rep,4,Paris,+33 14 723 4404,43 Rue Jouffroy D'abbans,,,France,75017,EMEA

In [34]:
cur.execute("""SELECT firstName, lastName FROM employees
                                JOIN offices 
                                ON employees.officeCode = offices.officeCode
                                WHERE city = 'Boston';""").fetchall()

[('Julie', 'Firrelli'), ('Steve', 'Patterson')]

## Are there any offices that have zero employees?
Hint: Combine the employees and offices tables and use a group by.

In [35]:
cur.execute("""SELECT city,count(*) FROM employees
            JOIN offices
            USING(officeCode)
            GROUP BY 1""").fetchall()

[('Boston', 2),
 ('London', 2),
 ('NYC', 2),
 ('Paris', 5),
 ('San Francisco', 6),
 ('Sydney', 4),
 ('Tokyo', 2)]

## Write 3 Questions of your own and answer them

In [8]:
# Answers will vary
# Example: Display the htmlDescription and employee's first and last name for each product that each employee has sold

In [49]:
cur.execute("""SELECT firstName, lastName, productName FROM employees
            JOIN customers
            ON employees.employeeNumber = customers.salesRepEmployeeNumber
            JOIN orders
            USING(customerNumber)
            JOIN orderdetails
            USING(orderNumber)
            JOIN products
            USING(productCode);""").fetchall()

[('Leslie', 'Jennings', '1958 Setra Bus'),
 ('Leslie', 'Jennings', '1940 Ford Pickup Truck'),
 ('Leslie', 'Jennings', '1939 Cadillac Limousine'),
 ('Leslie', 'Jennings', '1996 Peterbilt 379 Stake Bed with Outrigger'),
 ('Leslie', 'Jennings', '1968 Ford Mustang'),
 ('Leslie', 'Jennings', '1968 Dodge Charger'),
 ('Leslie', 'Jennings', '1970 Plymouth Hemi Cuda'),
 ('Leslie', 'Jennings', '1969 Dodge Charger'),
 ('Leslie', 'Jennings', '1948 Porsche 356-A Roadster'),
 ('Leslie', 'Jennings', '1969 Dodge Super Bee'),
 ('Leslie', 'Jennings', '1976 Ford Gran Torino'),
 ('Leslie', 'Jennings', '1957 Vespa GS150'),
 ('Leslie', 'Jennings', '1957 Corvette Convertible'),
 ('Leslie', 'Jennings', '1982 Ducati 900 Monster'),
 ('Leslie', 'Jennings', '1982 Lamborghini Diablo'),
 ('Leslie', 'Jennings', '1971 Alpine Renault 1600s'),
 ('Leslie', 'Jennings', '1956 Porsche 356A Coupe'),
 ('Leslie', 'Jennings', '1961 Chevrolet Impala'),
 ('Leslie', 'Jennings', '1982 Ducati 996 R'),
 ('Leslie', 'Jennings', '1974 Ducati 350 Mk3 Desmo'),
 ('Leslie', 'Jennings', '2002 Yamaha YZR M1'),
 ('Leslie', 'Jennings', '2001 Ferrari Enzo'),
 ('Leslie', 'Jennings', '1969 Corvair Monza'),
 ('Leslie', 'Jennings', '1969 Ford Falcon'),
 ('Leslie', 'Jennings', '1903 Ford Model A'),
 ('Leslie', 'Jennings', 'Collectable Wooden Train'),
 ('Leslie', 'Jennings', '1970 Triumph Spitfire'),
 ('Leslie', 'Jennings', '1904 Buick Runabout'),
 ('Leslie', 'Jennings', '18th century schooner'),
 ('Leslie', 'Jennings', '1912 Ford Model T Delivery Wagon'),
 ('Leslie', 'Jennings', "1950's Chicago Surface Lines Streetcar"),
 ('Leslie', 'Jennings', '1962 City of Detroit Streetcar'),
 ('Leslie', 'Jennings', 'The Schooner Bluenose'),
 ('Leslie', 'Jennings', 'The Mayflower'),
 ('Leslie', 'Jennings', 'The Titanic'),
 ('Leslie', 'Jennings', 'The Queen Mary'),
 ('Leslie', 'Jennings', 'Pont Yacht'),
 ('Leslie', 'Jennings', '1937 Lincoln Berline'),
 ('Leslie', 'Jennings', '1936 Mercedes-Benz 500K Special Roadster'),
 ('Leslie', 'Jennings', '1917 Grand Touring Sedan'),
 ('Leslie', 'Jennings', '1911 Ford Town Car'),
 ('Leslie', 'Jennings', '1932 Model A Ford J-Coupe'),
 ('Leslie', 'Jennings', '1928 Mercedes-Benz SSK'),
 ('Leslie', 'Jennings', '1917 Maxwell Touring Car'),
 ('Leslie', 'Jennings', '1932 Alfa Romeo 8C2300 Spider Sport'),
 ('Leslie', 'Jennings', '1957 Ford Thunderbird'),
 ('Leslie', 'Jennings', '1970 Chevy Chevelle SS 454'),
 ('Leslie', 'Jennings', '1939 Chevrolet Deluxe Coupe'),
 ('Leslie', 'Jennings', '1938 Cadillac V-16 Presidential Limousine'),
 ('Leslie', 'Jennings', '1949 Jaguar XK 120'),
 ('Leslie', 'Jennings', '1952 Citroen-15CV'),
 ('Leslie', 'Jennings', '1969 Chevrolet Camaro Z28'),
 ('Leslie', 'Jennings', '2002 Chevy Corvette'),
 ('Leslie', 'Jennings', '1936 Mercedes Benz 500k Roadster'),
 ('Leslie', 'Jennings', '1962 LanciaA Delta 16V'),
 ('Leslie', 'Jennings', '1958 Setra Bus'),
 ('Leslie', 'Jennings', '1957 Chevy Pickup'),
 ('Leslie', 'Jennings', '1964 Mercedes Tour Bus'),
 ('Leslie', 'Jennings', '1926 Ford Fire Engine'),
 ('Leslie', 'Jennings', '1992 Ferrari 360 Spider red'),
 ('Leslie', 'Jennings', '1940s Ford truck'),
 ('Leslie', 'Jennings', '1939 Cadillac Limousine'),
 ('Leslie', 'Jennings', '1962 Volkswagen Microbus'),
 ('Leslie', 'Jennings', '1958 Chevy Corvette Limited Edition'),
 ('Leslie', 'Jennings', '1980’s GM Manhattan Express'),
 ('Leslie', 'Jennings', '1954 Greyhound Scenicruiser'),
 ('Leslie', 'Jennings', '1996 Peterbilt 379 Stake Bed with Outrigger'),
 ('Leslie', 'Jennings', '1982 Camaro Z28'),
 ('Leslie', 'Jennings', '1957 Chevy Pickup'),
 ('Leslie', 'Jennings', '1998 Chrysler Plymouth Prowler'),
 ('Leslie', 'Jennings', '1964 Mercedes Tour Bus'),
 ('Leslie', 'Jennings', '1926 Ford Fire Engine'),
 ('Leslie', 'Jennings', '1992 Ferrari 360 Spider red'),
 ('Leslie', 'Jennings', '1970 Dodge Coronet'),
 ('Leslie', 'Jennings', '1962 Volkswagen Microbus'),
 ('Leslie', 'Jennings', '1958 Chevy Corvette Limited Edition'),
 ('Leslie', 'Jennings', '1992 Porsche Cayenne Turbo Silver'),
 ('Leslie', 'Jennings', '1954 Greyhound Scenicruiser'),
 ('Leslie', 'Jennings', 'Diamond T620 Semi-Skirted Tanker'),
 ('Leslie', 'Jennings', '2001 Ferrari Enzo'),
 ('Leslie', 'Jennings', '1969 Corvair Monza'),
 ('Leslie', 'Jennings', '1969 Ford Falcon'),
 ('Leslie', 'Jennings', '1998 Chrysler Plymouth Prowler'),
 ('Leslie', 'Jennings', '1903 Ford Model A'),
 ('Leslie', 'Jennings', 'Collectable Wooden Train'),
 ('Leslie', 'Jennings', '1970 Triumph Spitfire'),
 ('Leslie', 'Jennings', '1970 Dodge Coronet'),
 ('Leslie', 'Jennings', '1992 Porsche Cayenne Turbo Silver'),
 ('Leslie', 'Jennings', "1950's Chicago Surface Lines Streetcar"),
 ('Leslie', 'Jennings', 'Diamond T620 Semi-Skirted Tanker'),
 ('Leslie', 'Jennings', '1962 City of Detroit Streetcar'),
 ('Leslie', 'Jennings', 'The Mayflower'),
 ('Leslie', 'Jennings', '1952 Alpine Renault 1300'),
 ('Leslie', 'Jennings', '1940 Ford Pickup Truck'),
 ('Leslie', 'Jennings', '1937 Lincoln Berline'),
 ('Leslie', 'Jennings', '1936 Mercedes-Benz 500K Special Roadster'),
 ('Leslie', 'Jennings', '1917 Grand Touring Sedan'),
 ('Leslie', 'Jennings', '1911 Ford Town Car'),
 ('Leslie', 'Jennings', '1932 Model A Ford J-Coupe'),
 ('Leslie', 'Jennings', '1928 Mercedes-Benz SSK'),
 ('Leslie', 'Jennings', '1913 Ford Model T Speedster'),
 ('Leslie', 'Jennings', '1934 Ford V8 Coupe'),
 ('Leslie', 'Jennings', '18th Century Vintage Horse Carriage'),
 ('Leslie', 'Jennings', '1917 Maxwell Touring Car'),
 ('Leslie', 'Jennings', '1939 Cadillac Limousine'),
 ('Leslie', 'Jennings', '1939 Chevrolet Deluxe Coupe'),
 ('Leslie', 'Jennings', '1938 Cadillac V-16 Presidential Limousine'),
 ('Leslie', 'Jennings', '1936 Mercedes Benz 500k Roadster'),
 ('Leslie', 'Jennings', '1936 Chrysler Airflow'),
 ('Leslie', 'Jennings', '1958 Chevy Corvette Limited Edition'),
 ('Leslie', 'Jennings', '1980’s GM Manhattan Express'),
 ('Leslie', 'Jennings', '1954 Greyhound Scenicruiser'),
 ('Leslie', 'Jennings', '1952 Alpine Renault 1300'),
 ('Leslie', 'Jennings', '1962 LanciaA Delta 16V'),
 ('Leslie', 'Jennings', '1958 Setra Bus'),
 ('Leslie', 'Jennings', '1940 Ford Pickup Truck'),
 ('Leslie', 'Jennings', '1926 Ford Fire Engine'),
 ('Leslie', 'Jennings', '1913 Ford Model T Speedster'),
 ('Leslie', 'Jennings', '1934 Ford V8 Coupe'),
 ('Leslie', 'Jennings', '18th Century Vintage Horse Carriage'),
 ('Leslie', 'Jennings', '1917 Maxwell Touring Car'),
 ('Leslie', 'Jennings', '1940s Ford truck'),
 ('Leslie', 'Jennings', '1949 Jaguar XK 120'),
 ('Leslie', 'Jennings', '1952 Citroen-15CV'),
 ('Leslie', 'Jennings', '1969 Chevrolet Camaro Z28'),
 ('Leslie', 'Jennings', '2002 Chevy Corvette'),
 ('Leslie', 'Jennings', '1936 Mercedes Benz 500k Roadster'),
 ('Leslie', 'Jennings', '2001 Ferrari Enzo'),
 ('Leslie', 'Jennings', '1957 Chevy Pickup'),
 ('Leslie', 'Jennings', '1998 Chrysler Plymouth Prowler'),
 ('Leslie', 'Jennings', '1970 Dodge Coronet'),
 ('Leslie', 'Jennings', '1962 Volkswagen Microbus'),
 ('Leslie', 'Jennings', '1958 Chevy Corvette Limited Edition'),
 ('Leslie', 'Jennings', '1992 Porsche Cayenne Turbo Silver'),
 ('Leslie', 'Jennings', '1980’s GM Manhattan Express'),
 ('Leslie', 'Jennings', '1954 Greyhound Scenicruiser'),
 ('Leslie', 'Jennings', "1950's Chicago Surface Lines Streetcar"),
 ('Leslie', 'Jennings', 'Diamond T620 Semi-Skirted Tanker'),
 ('Leslie', 'Jennings', '1982 Camaro Z28'),
 ('Leslie', 'Jennings', '2001 Ferrari Enzo'),
 ('Leslie', 'Jennings', '1969 Corvair Monza'),
 ('Leslie', 'Jennings', '1969 Ford Falcon'),
 ('Leslie', 'Jennings', '1957 Chevy Pickup'),
 ('Leslie', 'Jennings', '1998 Chrysler Plymouth Prowler'),
 ('Leslie', 'Jennings', '1917 Maxwell Touring Car'),
 ('Leslie', 'Jennings', '1940s Ford truck'),
 ('Leslie', 'Jennings', '1939 Cadillac Limousine'),
 ('Leslie', 'Jennings', '1962 Volkswagen Microbus'),
 ('Leslie', 'Jennings', '1936 Chrysler Airflow'),
 ('Leslie', 'Jennings', '1980’s GM Manhattan Express'),
 ('Leslie', 'Jennings', '1996 Peterbilt 379 Stake Bed with Outrigger'),
 ('Leslie', 'Jennings', '1982 Camaro Z28'),
 ('Leslie', 'Jennings', '1940 Ford Delivery Sedan'),
 ('Leslie', 'Jennings', 'The Schooner Bluenose'),
 ('Leslie', 'Jennings', '1993 Mazda RX-7'),
 ('Leslie', 'Jennings', '1995 Honda Civic'),
 ('Leslie', 'Jennings', '1932 Model A Ford J-Coupe'),
 ('Leslie', 'Jennings', '1928 Mercedes-Benz SSK'),
 ('Leslie', 'Jennings', '1969 Dodge Super Bee'),
 ('Leslie', 'Jennings', '1976 Ford Gran Torino'),
 ('Leslie', 'Jennings', '1957 Vespa GS150'),
 ('Leslie', 'Jennings', '1957 Corvette Convertible'),
 ('Leslie', 'Jennings', '1982 Ducati 900 Monster'),
 ('Leslie', 'Jennings', '1982 Lamborghini Diablo'),
 ('Leslie', 'Jennings', '1971 Alpine Renault 1600s'),
 ('Leslie', 'Jennings', '1956 Porsche 356A Coupe'),
 ('Leslie', 'Jennings', '1961 Chevrolet Impala'),
 ('Leslie', 'Jennings', '1982 Ducati 996 R'),
 ('Leslie', 'Jennings', '1974 Ducati 350 Mk3 Desmo'),
 ('Leslie', 'Jennings', '2002 Yamaha YZR M1'),
 ('Leslie', 'Jennings', '1969 Ford Falcon'),
 ('Leslie', 'Jennings', '1903 Ford Model A'),
 ('Leslie', 'Jennings', 'Collectable Wooden Train'),
 ('Leslie', 'Jennings', '1904 Buick Runabout'),
 ('Leslie', 'Jennings', '18th century schooner'),
 ('Leslie', 'Jennings', '1912 Ford Model T Delivery Wagon'),
 ('Leslie', 'Jennings', '1940 Ford Delivery Sedan'),
 ('Leslie', 'Jennings', 'The Schooner Bluenose'),
 ('Leslie', 'Jennings', '1928 Mercedes-Benz SSK'),
 ('Leslie', 'Jennings', '1938 Cadillac V-16 Presidential Limousine'),
 ('Leslie', 'Jennings', '1937 Lincoln Berline'),
 ('Leslie', 'Jennings', '1936 Mercedes-Benz 500K Special Roadster'),
 ('Leslie', 'Jennings', '1934 Ford V8 Coupe'),
 ('Leslie', 'Jennings', '18th Century Vintage Horse Carriage'),
 ('Leslie', 'Jennings', '1917 Maxwell Touring Car'),
 ('Leslie', 'Jennings', '1936 Chrysler Airflow'),
 ('Leslie', 'Jennings', '1969 Harley Davidson Ultimate Chopper'),
 ('Leslie', 'Jennings', '1996 Moto Guzzi 1100i'),
 ('Leslie', 'Jennings', '2003 Harley-Davidson Eagle Drag Bike'),
 ('Leslie', 'Jennings', '2002 Suzuki XREO'),
 ('Leslie', 'Jennings', '1936 Harley Davidson El Knucklehead'),
 ('Leslie', 'Jennings', '1997 BMW R 1100 S'),
 ('Leslie', 'Jennings', '1960 BSA Gold Star DBD34'),
 ('Leslie', 'Jennings', '1952 Alpine Renault 1300'),
 ('Leslie', 'Jennings', '1958 Setra Bus'),
 ('Leslie', 'Jennings', '1940 Ford Pickup Truck'),
 ('Leslie', 'Jennings', '1913 Ford Model T Speedster'),
 ('Leslie', 'Jennings', '1917 Maxwell Touring Car'),
 ('Leslie', 'Jennings', '1939 Cadillac Limousine'),
 ('Leslie', 'Jennings', '1936 Chrysler Airflow'),
 ('Leslie', 'Jennings', '1996 Peterbilt 379 Stake Bed with Outrigger'),
 ('Leslie', 'Jennings', '1952 Alpine Renault 1300'),
 ('Leslie', 'Jennings', '1962 LanciaA Delta 16V'),
 ('Leslie', 'Jennings', '1958 Setra Bus'),
 ('Leslie', 'Jennings', '1940 Ford Pickup Truck'),
 ('Leslie', 'Jennings', '1926 Ford Fire Engine'),
 ('Leslie', 'Jennings', '1940s Ford truck'),
 ('Leslie', 'Jennings', '1939 Cadillac Limousine'),
 ('Leslie', 'Jennings', '1962 Volkswagen Microbus'),
 ('Leslie', 'Jennings', '1980’s GM Manhattan Express'),
 ('Leslie', 'Jennings', '1996 Peterbilt 379 Stake Bed with Outrigger'),
 ('Leslie', 'Jennings', '1982 Camaro Z28'),
 ('Leslie', 'Jennings', '1969 Harley Davidson Ultimate Chopper'),
 ('Leslie', 'Jennings', '1996 Moto Guzzi 1100i'),
 ('Leslie', 'Jennings', '2003 Harley-Davidson Eagle Drag Bike'),
 ('Leslie', 'Jennings', 'P-51-D Mustang'),
 ('Leslie', 'Jennings', '1936 Harley Davidson El Knucklehead'),
 ('Leslie', 'Jennings', '1997 BMW R 1100 S'),
 ('Leslie', 'Jennings', '1928 British Royal Navy Airplane'),
 ('Leslie', 'Jennings', '1960 BSA Gold Star DBD34'),
 ('Leslie', 'Jennings', 'Corsair F4U ( Bird Cage)'),
 ('Leslie', 'Jennings', '1900s Vintage Tri-Plane'),
 ('Leslie', 'Jennings', '1997 BMW F650 ST'),
 ('Leslie', 'Jennings', '1928 Ford Phaeton Deluxe'),
 ('Leslie', 'Jennings', '1930 Buick Marquette Phaeton'),
 ('Leslie', 'Jennings', 'American Airlines: B767-300'),
 ('Leslie', 'Jennings', 'America West Airlines B757-200'),
 ('Leslie', 'Jennings', 'ATA: B757-300'),
 ('Leslie', 'Jennings', 'F/A 18 Hornet 1/72'),
 ('Leslie', 'Jennings', 'American Airlines: MD-11S'),
 ('Leslie', 'Jennings', '1900s Vintage Tri-Plane'),
 ('Leslie', 'Jennings', '2003 Harley-Davidson Eagle Drag Bike'),
 ('Leslie', 'Jennings', '2002 Suzuki XREO'),
 ('Leslie', 'Jennings', '1936 Harley Davidson El Knucklehead'),
 ('Leslie', 'Jennings', '1997 BMW R 1100 S'),
 ('Leslie', 'Jennings', '1969 Harley Davidson Ultimate Chopper'),
 ('Leslie', 'Jennings', '1996 Moto Guzzi 1100i'),
 ('Leslie', 'Jennings', '2003 Harley-Davidson Eagle Drag Bike'),
 ('Leslie', 'Jennings', '1968 Ford Mustang'),
 ('Leslie', 'Jennings', '2002 Suzuki XREO'),
 ('Leslie', 'Jennings', '1970 Plymouth Hemi Cuda'),
 ('Leslie', 'Jennings', '1936 Harley Davidson El Knucklehead'),
 ('Leslie', 'Jennings', '1969 Dodge Super Bee'),
 ('Leslie', 'Jennings', '1976 Ford Gran Torino'),
 ('Leslie', 'Jennings', '1957 Vespa GS150'),
 ('Leslie', 'Jennings', '1957 Corvette Convertible'),
 ('Leslie', 'Jennings', '1997 BMW R 1100 S'),
 ('Leslie', 'Jennings', '1982 Ducati 900 Monster'),
 ('Leslie', 'Jennings', '1971 Alpine Renault 1600s'),
 ('Leslie', 'Jennings', '1961 Chevrolet Impala'),
 ('Leslie', 'Jennings', '1982 Ducati 996 R'),
 ('Leslie', 'Jennings', '1974 Ducati 350 Mk3 Desmo'),
 ('Leslie', 'Jennings', '2002 Yamaha YZR M1'),
 ('Leslie', 'Jennings', '1937 Lincoln Berline'),
 ('Leslie', 'Jennings', '1936 Mercedes-Benz 500K Special Roadster'),
 ('Leslie', 'Jennings', '1917 Grand Touring Sedan'),
 ('Leslie', 'Jennings', '1911 Ford Town Car'),
 ('Leslie', 'Jennings', '1932 Model A Ford J-Coupe'),
 ('Leslie', 'Jennings', '1928 Mercedes-Benz SSK'),
 ('Leslie', 'Jennings', '1932 Alfa Romeo 8C2300 Spider Sport'),
 ('Leslie', 'Jennings', '1939 Chevrolet Deluxe Coupe'),
 ('Leslie', 'Jennings', '1938 Cadillac V-16 Presidential Limousine'),
 ('Leslie', 'Jennings', '1936 Mercedes Benz 500k Roadster'),
 ('Leslie', 'Jennings', '1952 Alpine Renault 1300'),
 ('Leslie', 'Jennings', '1962 LanciaA Delta 16V'),
 ('Leslie', 'Jennings', '1958 Setra Bus'),
 ('Leslie', 'Jennings', '1940 Ford Pickup Truck'),
 ('Leslie', 'Jennings', '1936 Mercedes-Benz 500K Special Roadster'),
 ('Leslie', 'Jennings', '1926 Ford Fire Engine'),
 ('Leslie', 'Jennings', '1913 Ford Model T Speedster'),
 ('Leslie', 'Jennings', '1934 Ford V8 Coupe'),
 ('Leslie', 'Jennings', '18th Century Vintage Horse Carriage'),
 ('Leslie', 'Jennings', '1972 Alfa Romeo GTA'),
 ('Leslie', 'Jennings', '18th century schooner'),
 ('Leslie', 'Jennings', '1912 Ford Model T Delivery Wagon'),
 ('Leslie', 'Jennings', 'The Mayflower'),
 ('Leslie', 'Jennings', '1980s Black Hawk Helicopter'),
 ('Leslie', 'Jennings', 'P-51-D Mustang'),
 ('Leslie', 'Jennings', '1928 British Royal Navy Airplane'),
 ('Leslie', 'Jennings', '1960 BSA Gold Star DBD34'),
 ('Leslie', 'Jennings', 'Corsair F4U ( Bird Cage)'),
 ('Leslie', 'Jennings', '1900s Vintage Tri-Plane'),
 ('Leslie', 'Jennings', '1997 BMW F650 ST'),
 ('Leslie', 'Jennings', '1928 Ford Phaeton Deluxe'),
 ('Leslie', 'Jennings', '1930 Buick Marquette Phaeton'),
 ('Leslie', 'Jennings', 'American Airlines: B767-300'),
 ('Leslie', 'Jennings', 'America West Airlines B757-200'),
 ('Leslie', 'Jennings', 'ATA: B757-300'),
 ('Leslie', 'Jennings', 'F/A 18 Hornet 1/72'),
 ('Leslie', 'Jennings', 'American Airlines: MD-11S'),
 ('Leslie', 'Jennings', '1913 Ford Model T Speedster'),
 ('Leslie', 'Jennings', '1934 Ford V8 Coupe'),
 ('Leslie', 'Jennings', '18th Century Vintage Horse Carriage'),
 ('Leslie', 'Jennings', '1917 Maxwell Touring Car'),
 ('Leslie', 'Jennings', '1936 Chrysler Airflow'),
 ('Leslie', 'Jennings', '1972 Alfa Romeo GTA'),
 ('Leslie', 'Jennings', '1980s Black Hawk Helicopter'),
 ('Leslie', 'Jennings', '1999 Yamaha Speed Boat'),
 ('Leslie', 'Jennings', '1941 Chevrolet Special Deluxe Cabriolet'),
 ('Leslie', 'Jennings', '1900s Vintage Bi-Plane'),
 ('Leslie', 'Jennings', '1937 Horch 930V Limousine'),
 ('Leslie', 'Jennings', '1940 Ford Delivery Sedan'),
 ('Leslie', 'Jennings', 'HMS Bounty'),
 ('Leslie', 'Jennings', 'Boeing X-32A JSF'),
 ('Leslie', 'Jennings', '1965 Aston Martin DB5'),
 ('Leslie', 'Jennings', '1917 Grand Touring Sedan'),
 ('Leslie', 'Jennings', '1911 Ford Town Car'),
 ('Leslie', 'Jennings', '1999 Indy 500 Monte Carlo SS'),
 ('Leslie', 'Jennings', '1932 Alfa Romeo 8C2300 Spider Sport'),
 ('Leslie', 'Jennings', '1957 Ford Thunderbird'),
 ('Leslie', 'Jennings', '1970 Chevy Chevelle SS 454'),
 ('Leslie', 'Jennings', '1966 Shelby Cobra 427 S/C'),
 ('Leslie', 'Jennings', '1949 Jaguar XK 120'),
 ('Leslie', 'Jennings', '1952 Citroen-15CV'),
 ('Leslie', 'Jennings', '1969 Chevrolet Camaro Z28'),
 ('Leslie', 'Jennings', '2002 Chevy Corvette'),
 ('Leslie', 'Jennings', '1937 Lincoln Berline'),
 ('Leslie', 'Jennings', '1936 Mercedes-Benz 500K Special Roadster'),
 ('Leslie', 'Jennings', '1917 Grand Touring Sedan'),
 ('Leslie', 'Jennings', '1911 Ford Town Car'),
 ('Leslie', 'Jennings', '1932 Model A Ford J-Coupe'),
 ('Leslie', 'Jennings', '1928 Mercedes-Benz SSK'),
 ('Leslie', 'Jennings', '1917 Maxwell Touring Car'),
 ('Leslie', 'Jennings', '1939 Chevrolet Deluxe Coupe'),
 ('Leslie', 'Jennings', '1938 Cadillac V-16 Presidential Limousine'),
 ('Leslie', 'Jennings', '1936 Mercedes Benz 500k Roadster'),
 ('Leslie', 'Jennings', '1936 Chrysler Airflow'),
 ('Leslie', 'Jennings', '1957 Chevy Pickup'),
 ('Leslie', 'Jennings', '1998 Chrysler Plymouth Prowler'),
 ('Leslie', 'Jennings', '1958 Chevy Corvette Limited Edition'),
 ('Leslie', 'Jennings', '1954 Greyhound Scenicruiser'),
 ('Leslie', 'Thompson', '1917 Grand Touring Sedan'),
 ('Leslie', 'Thompson', '1911 Ford Town Car'),
 ('Leslie', 'Thompson', '1932 Model A Ford J-Coupe'),
 ('Leslie', 'Thompson', '1932 Alfa Romeo 8C2300 Spider Sport'),
 ('Leslie', 'Thompson', '1957 Ford Thunderbird'),
 ('Leslie', 'Thompson', '1970 Chevy Chevelle SS 454'),
 ('Leslie', 'Thompson', '1939 Chevrolet Deluxe Coupe'),
 ('Leslie', 'Thompson', '1938 Cadillac V-16 Presidential Limousine'),
 ('Leslie', 'Thompson', '1949 Jaguar XK 120'),
 ('Leslie', 'Thompson', '1952 Citroen-15CV'),
 ('Leslie', 'Thompson', '1969 Chevrolet Camaro Z28'),
 ('Leslie', 'Thompson', '2002 Chevy Corvette'),
 ('Leslie', 'Thompson', '1936 Mercedes Benz 500k Roadster'),
 ('Leslie', 'Thompson', '1993 Mazda RX-7'),
 ('Leslie', 'Thompson', '1965 Aston Martin DB5'),
 ('Leslie', 'Thompson', '1948 Porsche 356-A Roadster'),
 ('Leslie', 'Thompson', '1995 Honda Civic'),
 ('Leslie', 'Thompson', '1999 Indy 500 Monte Carlo SS'),
 ('Leslie', 'Thompson', '1992 Ferrari 360 Spider red'),
 ('Leslie', 'Thompson', '1948 Porsche Type 356 Roadster'),
 ('Leslie', 'Thompson', '1966 Shelby Cobra 427 S/C'),
 ('Leslie', 'Thompson', '1982 Lamborghini Diablo'),
 ('Leslie', 'Thompson', '1956 Porsche 356A Coupe'),
 ('Leslie', 'Thompson', '1937 Lincoln Berline'),
 ('Leslie', 'Thompson', '1949 Jaguar XK 120'),
 ('Leslie', 'Thompson', '1952 Citroen-15CV'),
 ('Leslie', 'Thompson', '1969 Chevrolet Camaro Z28'),
 ('Leslie', 'Thompson', '2002 Chevy Corvette'),
 ('Leslie', 'Thompson', '1936 Mercedes Benz 500k Roadster'),
 ('Leslie', 'Thompson', '1969 Harley Davidson Ultimate Chopper'),
 ('Leslie', 'Thompson', '1996 Moto Guzzi 1100i'),
 ('Leslie', 'Thompson', '2003 Harley-Davidson Eagle Drag Bike'),
 ('Leslie', 'Thompson', '2002 Suzuki XREO'),
 ('Leslie', 'Thompson', 'P-51-D Mustang'),
 ('Leslie', 'Thompson', '1936 Harley Davidson El Knucklehead'),
 ('Leslie', 'Thompson', '1997 BMW R 1100 S'),
 ('Leslie', 'Thompson', '1928 British Royal Navy Airplane'),
 ('Leslie', 'Thompson', '1960 BSA Gold Star DBD34'),
 ('Leslie', 'Thompson', '1982 Ducati 900 Monster'),
 ('Leslie', 'Thompson', '1900s Vintage Tri-Plane'),
 ('Leslie', 'Thompson', '1997 BMW F650 ST'),
 ('Leslie', 'Thompson', '1982 Ducati 996 R'),
 ('Leslie', 'Thompson', '1974 Ducati 350 Mk3 Desmo'),
 ('Leslie', 'Thompson', '2002 Yamaha YZR M1'),
 ('Leslie', 'Thompson', 'ATA: B757-300'),
 ('Leslie', 'Thompson', '2002 Suzuki XREO'),
 ('Leslie', 'Thompson', '1965 Aston Martin DB5'),

In [53]:
# Your code here
cur.execute("""SELECT firstName, lastName, count(productName) AS count FROM employees
            JOIN customers
            ON employees.employeeNumber = customers.salesRepEmployeeNumber
            JOIN orders
            USING(customerNumber)
            JOIN orderdetails
            USING(orderNumber)
            JOIN products
            USING(productCode)
            GROUP BY firstName
            ORDER BY count DESC;""").fetchall()

[('Leslie', 'Jennings', 445),
 ('Gerard', 'Hernandez', 396),
 ('Pamela', 'Castillo', 272),
 ('Larry', 'Bott', 236),
 ('Barry', 'Jones', 220),
 ('George', 'Vanauf', 211),
 ('Andy', 'Fixter', 185),
 ('Peter', 'Marsh', 185),
 ('Loui', 'Bondur', 177),
 ('Steve', 'Patterson', 152),
 ('Foon Yue', 'Tseng', 142),
 ('Mami', 'Nishi', 137),
 ('Julie', 'Firrelli', 124),
 ('Martin', 'Gerard', 114)]

In [10]:
# Your code here

In [11]:
# Your code here

## Level Up: Display the names of every individual product that each employee has sold

In [13]:
# Your code here
cur.execute("""SELECT firstName, lastName, productName FROM employees
            JOIN customers
            ON employees.employeeNumber = customers.salesRepEmployeeNumber
            JOIN orders
            USING(customerNumber)
            JOIN orderdetails
            USING(orderNumber)
            JOIN products
            USING(productCode);""").fetchall()

## Level Up: Display the Number of Products each employee has sold

In [15]:
# Your code here

## Summary

Congrats! You now know how to use join statements, along with leveraging your foreign keys knowledge!